name: strava_nicola
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pyqt
  - notebook
  - matplotlib
  - numpy
  - pandas
  - setuptools
  - scipy
  - requests
  - urllib3
  - datetime
